title: Saya bersih, Bavak!
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Perkataan-perkataan yang terhilang dari jpmrblood.
permalink: ':year/:month/:day/:title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "http://localhost:3000" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Jan Peter Alexander Rajagukguk # add your name
author-pic: jp-face.jpg
about-author: Saya seorang yang suka menulis.

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: jpmrblood # Add your Github handle
twitter: '@jpmrblood' # Add your Twitter handle
facebook: 'jpmrblood' # Add your Facebook handle
instagram: 'jpmrblood' # Add your Instagram handle
googleplus: JanPeterAlexanderRajagukguk # Add your Google Plus handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: 'saya-bersih-bavak' # Add your discus identifier

# Tracker
analytics: 'UA-30764858-1' # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
